version: "3.9"

services:
  api:
    build: 
      context: ./
      dockerfile: docker.api.dockerfile
    restart: always
    # replace with expose:8000 as soon as traefik is setup
    ports:
      - "8000:8000" 

    volumes:
      - ../src/api/api.py:/app/api.py
      - ./assets/data.json:/app/data.json
    depends_on:
      - db
    networks:
      - backend


  db:
    image: mysql:oracle
    env_file: ./assets/db.env
    restart: always
    # ports only exposed for manual checks via dbeaver
    ports:
    - "3306:3306"

    volumes:
      - ../db/data:/var/lib/mysql
    networks:
      - backend


  scraper:
    build: 
      context: ./
      dockerfile: docker.scraper.dockerfile
    depends_on:
      - db
    env_file: ./assets/scraper.env
    volumes:
      - ../src/scraper/:/app/src
      - .assets/data.json:/app/assets/data.json

networks:
  backend: